# Generated by Django 4.2.4 on 2023-08-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='ClassAcademy',
        ),
        migrations.AddField(
            model_name='teacher',
            name='lessons_day',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='teacher',
            name='session_week',
            field=models.IntegerField(default=1),
        ),
    ]
