# Generated by Django 4.0.2 on 2023-08-16 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_class_classacademy_teacher_lessons_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='class_academy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.classacademy'),
        ),
    ]
