# Generated by Django 4.0.2 on 2023-08-16 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_teacher_class_academy'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.teacher'),
            preserve_default=False,
        ),
    ]
