# Generated by Django 4.0.2 on 2023-08-16 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_schedule_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='building',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.building'),
        ),
    ]
