# Generated by Django 4.0.2 on 2023-08-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_teacher_classroom_remove_teacher_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classacademy',
            name='grade',
        ),
        migrations.AlterField(
            model_name='group',
            name='shift',
            field=models.CharField(choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino')], default='Matutino', max_length=20, verbose_name='Turno'),
        ),
    ]
