# Generated by Django 4.0.2 on 2023-08-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_classacademy_grade_alter_group_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='classacademy',
            name='group',
            field=models.ManyToManyField(to='projects.Group'),
        ),
    ]
