# Generated by Django 4.0.2 on 2023-08-16 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_classacademy_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classacademy',
            name='group',
        ),
    ]
