# Generated by Django 4.0.2 on 2023-08-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_classacademy_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='four_month_period',
        ),
        migrations.AlterField(
            model_name='classacademy',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='teacher',
        ),
        migrations.AddField(
            model_name='schedule',
            name='teacher',
            field=models.ManyToManyField(to='projects.Teacher'),
        ),
    ]
