# Generated by Django 4.0.2 on 2023-08-16 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_schedule_four_month_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='teacher',
        ),
    ]
