# Generated by Django 4.0.2 on 2023-08-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_schedule_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='day_week',
        ),
        migrations.AddField(
            model_name='schedule',
            name='teacher',
            field=models.ManyToManyField(to='projects.Teacher'),
        ),
    ]
