# Generated by Django 4.0.2 on 2023-08-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_remove_schedule_day_week_schedule_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='classacademy',
            name='groups',
            field=models.ManyToManyField(to='projects.Group'),
        ),
    ]
