# Generated by Django 4.0.2 on 2023-08-29 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_classacademy_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='rol_classroom',
        ),
        migrations.AddField(
            model_name='classroom',
            name='rol',
            field=models.CharField(choices=[('Aula Compartida', 'Aula Compartida'), ('Aula fija', 'Aula fija')], default='Aula compartida', max_length=20, verbose_name='Tipo de aula'),
        ),
    ]
