# Generated by Django 4.0.2 on 2023-08-29 01:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_remove_classroom_rol_classroom_classroom_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='lessons_day',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='session_week',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
