# Generated by Django 4.0.2 on 2023-09-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_alter_schedule_number_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subjects_taught',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='class_academy',
        ),
        migrations.AddField(
            model_name='teacher',
            name='class_academy',
            field=models.ManyToManyField(to='projects.ClassAcademy'),
        ),
    ]
