# Generated by Django 4.0.2 on 2023-09-04 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_remove_teacher_subjects_taught_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classacademy',
            name='groups',
        ),
        migrations.AddField(
            model_name='classacademy',
            name='groups',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.group'),
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='class_academy',
        ),
        migrations.AddField(
            model_name='teacher',
            name='class_academy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.classacademy'),
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='classrooms_assigned',
        ),
        migrations.AddField(
            model_name='teacher',
            name='classrooms_assigned',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.classroom'),
        ),
    ]
