# Generated by Django 4.0.2 on 2023-09-04 20:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_rename_teachers_schedule_teacher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='teacher',
            new_name='teachers',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='number_days',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Numero de dias'),
        ),
    ]
