# Generated by Django 4.2.4 on 2023-09-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_classacademy_color_classroom_color_subject_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('student_id', models.CharField(blank=True, max_length=10, unique=True, verbose_name='Número de Estudiante')),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='color',
        ),
        migrations.AddField(
            model_name='teacher',
            name='tuition',
            field=models.CharField(blank=True, max_length=12, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='rol',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tipo de aula'),
        ),
        migrations.AlterField(
            model_name='group',
            name='shift',
            field=models.CharField(blank=True, max_length=20, verbose_name='Turno'),
        ),
    ]
