# Generated by Django 4.2.4 on 2023-09-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_student_remove_teacher_color_teacher_tuition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tuition',
            field=models.CharField(blank=True, max_length=12, verbose_name='Matrícula'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='color',
            field=models.CharField(default='FFFFFFF', max_length=7, verbose_name='Color'),
        ),
    ]
