# Generated by Django 4.2.4 on 2023-09-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_student_tuition_teacher_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='classAcademy',
            field=models.ManyToManyField(to='projects.classacademy'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='classroom',
            field=models.ManyToManyField(to='projects.classroom'),
        ),
    ]
