# Generated by Django 4.2.4 on 2023-09-13 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_student_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Carrera')),
                ('description', models.TextField(blank=True, verbose_name='Descripción de la Carrera')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='career',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.career'),
        ),
    ]
