# Generated by Django 4.2.4 on 2023-09-13 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_classacademy_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='Career',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.career'),
        ),
        migrations.AlterField(
            model_name='classacademy',
            name='groups',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.group'),
        ),
    ]
